;------------------------------------------------------------------------------
; Filename: mfunc19.mac
; Description: Activate Spindle Orient Request
; Notes:
; Requires: CNC12 V5.06
; Revision Date: 19 JUL 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
; OrientComplete_I IS INP17 (#50017)
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100 

M3 S0                            ;Command 0 speed    
M94 /19                          ;Request spindle orient 
M101 /50017                      ;Wait for tool to orient

N1000