;------------------------------------------------------------------------------
; Filename: mfunc20.mac
; Description: Deactivate Spindle Orient Request
; Notes: Deactivates M3, M4, and M19
; Requires: CNC12 V5.06
; Revision Date: 19 JUL 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M95 /1/2/19

N1000