;------------------------------------------------------------------------------
; Filename: mfunc16.mac
; Description: Deactivate Tool Unclamp
; Notes:
; Requires: CNC12 V5.06
; Revision Date: 19 JUL 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
; ToolClamped_I IS INP21 (#50017)
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M95 /15                          ;Request Tool Clamp 
M101 /50017                      ;Wait for tool to clamp
G4 P.25

N1000