;------------------------------------------------------------------------------
; Filename: mfunc72.mac
; Description: Send Spindle to Low position
; Notes:
; Requires:
; Revision Date:
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M94 /72                          ;Request spindle to low position
G4 P.25                          ;Wait 250ms
M101 /70663						 ;Wait for SpindleMoveComplete_M

N1000