;------------------------------------------------------------------------------
; Filename: mfunc64.mac
; Description: Activate Front Posts
; Notes:
; Requires:
; Revision Date:
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M94 /64                          ;Activate Front Posts
G4 P.25                          ;Wait 250ms

N1000