;------------------------------------------------------------------------------
; Filename: mfunc15.mac
; Description: Activate Tool Unclamp
; Notes:
; Requires: CNC12 V5.06
; Revision Date: 19 JUL 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
; ZeroSpeed_I     IS INP12 (#50012)
; ToolUnclamped_I IS INP30 (#50030)
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M101 /50012                      ;Wait for spindle to stop     
M94 /15                          ;Request Tool unclamp 
M101 /50030                      ;Wait for tool to unclamp
G4 P10                           ;was p.25

N1000