;------------------------------------------------------------------------------
; Filename: mfunc71.mac
; Description: Send Spindle to Med position
; Notes:
; Requires:
; Revision Date:
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

IF #70661 THEN GOTO 1000		 ;Skip macro if already at mid position
IF #70660 THEN GOTO 500		     ;Skip M70 if already at high position

M70								 ;Request spindle to high position first

N500
M94 /71                          ;Request spindle to med position
M101 /70663						 ;Wait for SpindleMoveComplete_M

N1000