;------------------------------------------------------------------------------
; Filename: mfunc70.mac
; Description: Send Spindle to High position
; Notes:
; Requires:
; Revision Date:
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

IF #70660 THEN GOTO 1000		 ;Skip macro if already at high position

M94 /70                          ;Request spindle to high position
M101 /70663						 ;Wait for SpindleMoveComplete_M

N1000