;------------------------------------------------------------------------------
; Filename: mfunc18.mac
; Description: ATC Carousel Initialization
; Notes: Sets Carousel Position, Putback, and Tool to 1.
;		 Parameter 164 = 1, prompts operator to input current tool in spindle
;		 and current carousel position and sets those values instead of 1.
; Requires: CNC12 V5.06
; Revision Date: 19 JAN 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M94 /18                          ;Request Carousel Initialization
G4 P1
M95 /18                          ;End Carousel Initialization

N1000