;------------------------------------------------------------------------------
; Filename: mfunc50.mac
; Description: Tool Index +
; Notes:
; Requires: CNC12 V5.02
; Revision Date: 18 MAY 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
; DoingIndex_M IS MEM301 (#70301)
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M94 /50                          ;Send Index Up Request
G4 P.25                          ;Wait 250ms
M100 /70301                      ;Wait for DoingIndex_M to reset
IF #50001                        ;Prevent Lookahead
M95 /50                          ;End Index Up Request

N1000