;------------------------------------------------------------------------------
; Filename: mfunc80.mac
; Description: Activate Carousel In
; Notes: Move Carousel In Towards the Spindle
; Requires: CNC12 V5.06
; Revision Date: 19 JUL 2023
; Please see TB300 or the following link for tips on writing custom macros.
; https://www.centroidcnc.com/centroid_diy/downloads/acorn_documentation/centroid_cnc_macro_programming.pdf
;------------------------------------------------------------------------------
; Parameters:
;
; System Variables:
;
; PLC Variables:
; CarouselIsIn_I IS INP32 (#50032)
;
; User Variables:
;
;------------------------------------------------------------------------------
IF #50001                        ;Prevent lookahead from parsing past here
IF #4201 || #4202 THEN GOTO 1000 ;Skip macro if graphing or searching

N100

M94 /80                          ;Request Carousel in
M101 /50032                      ;Wait for carousel is in
G4 P.5                           ;Wait .5 sec for car debounce
M101 /50032                      ;Wait for carousel is in 

N1000